discordlogin/urls.py
from django.urls import path

from .views import (
    discord_login_redirect,
    get_authenticated_user
)

urlpatterns = [
    path('auth/user', get_authenticated_user, name="get_authenticated_user"),
    path('login/redirect', discord_login_redirect, name='discord_login_redirect')
]

stigapp/urls.py
from django.urls import path

from .views import (
    DiscordMessageListView,
    DiscordReactionListView,
    GardenMessageListView,
    TopMessageListView,
    # LeaderBoardView,
    home,
    about,
    page_not_found_404_view,
    export_csv,
    export_to_airtable,
    terms,
    privacy,
    # export_top_message_csv,
    # export_garden_message_csv,
    update_top_message_list,

)




urlpatterns = [
    # path('', home, name='home'),
    path('', home, name='home'),
    path('terms-of-service', terms, name='terms_of_service'),
    path('privacy-policy', privacy, name='privacy_policy'),
    path('garden-messages', GardenMessageListView.as_view(), name='garden_messages'),
    path('about', about, name='about'),
    path('messages', TopMessageListView.as_view(), name='messages'),
    # path('leaderboard', LeaderBoardView.as_view(), name='leaderboard-list'),
    # path('leaderboard/messages', DiscordMessageListView.as_view(), name='message-list'),
    # path('leaderboard/reactions', DiscordReactionListView.as_view(), name='reaction-list'),
    path('export_csv/<str:table>/<str:selected>/<str:test>', export_csv, name='export_csv'),
    path('export-airtable', export_to_airtable, name='export_to_airtable'),
    # path('export-tm', export_top_message_csv, name='export_topmessage'),
    # path('export-gm', export_garden_message_csv, name='export_gardenmessage'),
    path('update-tm', update_top_message_list, name='update_topmessage'),
]

stigsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from discordlogin import views


admin.site.site_header = 'Stigflow Admin'


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('stigapp.urls')),
    path('login', views.discord_login, name='login'),
    path('profile/<pk>', views.UserUpdateView.as_view(), name='profile'),
    path('communityprofile/<pk>', views.CommunityProfileUpdateView.as_view(), name='community-profile'),
    path('logout/', views.discord_logout, name='logout'),
    path("oauth2/", include('discordlogin.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

handler404 = 'stigapp.views.page_not_found_404_view'

discordlogin/models.py
import datetime
import hashlib
import time

from django.contrib.auth.models import (
    BaseUserManager,
    UserManager,
    AbstractBaseUser,
    AbstractUser,
)
from django.contrib.sites.models import Site, _simple_domain_name_validator, SiteManager
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

# from django.utils.translation import gettext_lazy as _

# Community profile settings


class CommunityProfile(models.Model):
    id = models.BigAutoField(primary_key=True)
    airtable_credentials = models.JSONField(
        blank=True,
        null=True,
        help_text="The Airtable key, base name, and table name associated with Stigsite"
    )
    monitored_channels = models.JSONField(
        blank=True,
        null=True,
        help_text="A list of channels within guilds the site will listen to"
    )
    monitored_guilds = models.JSONField(
        blank=True,
        null=True,
        help_text="A list of Discord guilds (servers) the site will listen to"
    )
    promotion_threshold = models.IntegerField()
    site_style = models.JSONField(
        blank=True,
        null=True,
        help_text="The Airtable key, base name, and table name associated with Stigsite"
    )
    community_name = models.CharField(max_length=100, blank=True, null=True)
    django_site_id = models.ForeignKey(
        Site,
        db_column='django_site_id',
        related_name="+",
        on_delete=models.CASCADE,
        null=True
    )
    community_members = models.JSONField(
        blank=True,
        null=True,
        help_text="A list of whitelisted members' Discord usernames"
    )
    enable_twitter_handle_request = models.BooleanField(default=False)

    class Meta:
        managed = False
        db_table = 'community_profile'

    def get_absolute_url(self):
        return reverse('community-profile', kwargs={'pk': self.pk})

    def check_unique_community_name(self, current_profile_id, current_profile_name_value):
        """
        Checks whether a profile is attempting to use the name of an existing profile

        Input:
        current_profile_id: id number of the profile being changed
        current_profile_name_value: the name the profile is changing to

        Output:
        Boolean
        """
        check = True
        community_profiles = CommunityProfile.objects.all()
        for profile in community_profiles:
            if profile.id == current_profile_id:
                continue
            if profile.community_name is None:
                if profile.community_name == current_profile_name_value:
                    check = False
                    return check
            elif profile.community_name.lower() == current_profile_name_value.lower():
                check = False
                return check
        return check

    def clean(self):
        """
        Calls appropriate checks on a CommunityProfile form submission.

        If all checks are passed, called the save method for Site and CommunityProfile

        If fails, raises a ValidationError
        """
        unique_community_name = self.check_unique_community_name(self.id, self.community_name)
        if unique_community_name:
            if self.community_name is None or self.community_name == '':
                raise ValidationError(_('The community_name cannot be empty'), code='invalid')
            site = Site.objects.get(pk=self.django_site_id.id)
            site.name = self.community_name
            site.save()
            self.save()
        else:
            raise ValidationError(_('Not a unique id'), code='invalid')
            print("Not unique")
            pass


class UserManager(UserManager):

    def check_for_admin_authorization(self, discord_tag):
        """ Checks against a hardcoded list to see if a user is approved for admin privileges"""

        check = [False, False]
        approved_staff_users = [
            'Sha#6179',
            'richa#0775',
            'GideonRo#3175',
            'Irem#3362',
            'enti#1546',
            'bear100#9085',
            'acidlazzer#5796',
        ]

        approved_admin_users = [
            # 'insert discord_tags',
            'thompsgj#8407',
            'hobs#3386',
            'hobs#9238',
            'ronent#2267',
            'mariadyshel#6267',
            'rochdikhalid#7903',
        ]
        if discord_tag in approved_staff_users:
            check = [True, False]
        elif discord_tag in approved_admin_users:
            check = [True, True]

        return check

    def get_hash_value(self, val=time.time()):
        hash = hashlib.sha1()
        hash.update(str(val).encode('utf-8'))

        return hash.hexdigest()[:7]

    def create_password(self):
        """  Makes a string for the mandatory, non-nullable password field.

        The password will not work even if a user knows it because authentication happens through Discord.
        """
        password = self.get_hash_value()
        return password

    def create_new_discord_user(self, user, password=None):
        """ Creates a user in the DiscordUser table.

        Uses the 'DiscordAuthenticationBackend' for authentication, not the standard Django auth backend.
        """

        # Sets up a default site for the user

        hash_value = self.get_hash_value()
        rehashed_value = self.get_hash_value(hash_value)
        site_name = f"temp{rehashed_value[0:4]}"
        site_domain = f"{site_name}.com"

        site_result = Site.objects.create(
            name=site_name,
            domain=site_domain
        )

        # Sets up a default community profile for the user
        community_profile = CommunityProfile.objects.create(
            airtable_credentials='{"key", ""}',
            monitored_channels='{"included", ""}',
            monitored_guilds='{"included", ""}',
            promotion_threshold=5,
            django_site_id=site_result,
            community_members='{"included": ""}',
            enable_twitter_handle_request=False
        )

        # Add a site
        # Add a community profile with a site (hash)
        # Add site to community profile

        discord_tag = '%s#%s' % (user['username'], user['discriminator'])
        permissions_arr = self.check_for_admin_authorization(discord_tag)

        new_user = self.model(
            email='test@test.com'
        )
        new_user.id = user['id']
        new_user.username = discord_tag
        new_user.discord_tag = discord_tag
        new_user.twitter_handle = ''
        new_user.twitter_username = ''
        new_user.avatar = user['avatar']
        new_user.public_flags = user['public_flags']
        new_user.flags = user['flags']
        new_user.locale = user['locale']
        new_user.mfa_enabled = user['mfa_enabled']
        new_user.active = True
        new_user.staff = permissions_arr[0]
        new_user.admin = permissions_arr[1]
        new_user.django_site_id = site_result
        new_user.community_profile_id = community_profile

        password = self.create_password()
        new_user.set_password(password)
        new_user.save(using=self._db)
        return new_user


class User(AbstractUser):
    """ A user who has logged in to stigsite through Discord """

    objects = UserManager()

    # Discord-specific user attributes
    id = models.BigIntegerField(primary_key=True)
    username = models.CharField(max_length=100, unique=True)
    discord_tag = models.CharField(max_length=100, unique=True)
    twitter_handle = models.CharField(max_length=100, blank=True, null=True)
    twitter_username = models.CharField(max_length=100, blank=True, null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    avatar = models.CharField(blank=True, null=True, max_length=100)
    public_flags = models.IntegerField()
    flags = models.IntegerField()
    locale = models.CharField(max_length=100)
    mfa_enabled = models.BooleanField()
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(default=timezone.now)

    django_site_id = models.ForeignKey(
        Site,
        verbose_name="Team URL",
        db_column='django_site_id',
        related_name="+",
        on_delete=models.CASCADE,
        null=True
    )
    community_profile_id = models.ForeignKey(
        CommunityProfile,
        db_column='community_profile_id',
        related_name="+",
        on_delete=models.CASCADE,
        null=True
    )
    # django_customsite_id = models.ForeignKey(
    #     Site,
    #     verbose_name="Team URL",
    #     db_column='django_customsite_id',
    #     related_name="+",
    #     on_delete=models.CASCADE,
    #     null=True
    # )
    # Django admin user attributes
    # authenticated = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=True)
    admin = models.BooleanField(default=True)
    email = models.CharField(max_length=255, default="test@test.com")
    requested_twitter_handle = models.BooleanField(default=False)

    USERNAME_FIELD = 'discord_tag'
    REQUIRED_FIELDS = []

    class Meta:
        managed = False
        db_table = 'auth_user'
        # app_label = 'user_data'

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.discord_tag

    def get_short_name(self):
        return self.discord_tag

    def has_perm(self, perm, obj=None):
        return True


discordlogin/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User


class UserCreationForm(forms.ModelForm):
    """ A custom form for the User admin view when adding an instance of a custom User

    UserAdmin in admin.py adds 'username' and 'id'.
    That is necessary to display those fields in this form
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "id")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.id = self.cleaned_data['id']
        user.username = self.cleaned_data['id']
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """ A custom form for the User admin view when editing an instance of a custom User """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = '__all__'

    def clean_password(self):
        return self.initial['password']

discordlogin/templates/discordlogin/community-profile.html
{% extends "stigapp/base.html" %}
{% load static %}

{% block content %}

    <div class="community-container mt-4 mb-4">
        {% if user.is_authenticated %}
            <div class="card">
                {% if form.non_field_errors %}
                    <div class="alert alert-dismissible alert-danger">
                        <strong> {{form.non_field_errors}} </strong>
                    </div>
                {% endif %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-header"> 
                        <h3 class="pt-2"> {{ user.community_profile_id.community_name }} </h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-lg-5">
                                <label for="id_community_name"> Community name: </label>
                                <input type="text" class="form-control" name="community_name" placeholder="Enter community name" value={{form.community_name.value}} max_length="100" id="id_community_name">
                            </div>
                            <div class="form-group col-lg-3">
                                <label for="id_promotion_threshold"> Promotion threshold: </label>
                                <input type="number" class="form-control" name="promotion_threshold" max_length="100" value={{form.promotion_threshold.value}} id="id_promotion_threshold" required>
                            </div>
                            <div class="form-group col-lg-4">
                                <div class="custom-control custom-switch">
                                    <input type="checkbox" class="custom-control-input" name="enable_twitter_handle_request" id="id_enable_twitter_handle_request" {% if form.enable_twitter_handle_request.value %} checked {% endif %}>
                                    <label class="custom-control-label" for="id_enable_twitter_handle_request"> Twitter handle request </label>
                                </div>
                            </div>
                        </div>
                        <label> Airtable credentials: </label>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="airtable_api_key" placeholder="Enter Airtable API key" max_length="100" id="id_airtable_api_key" value={{form.airtable_credentials.value}}>
                                </div>  
                                <div class="form-group">
                                    <input type="text" class="form-control" name="airtable_base" placeholder="Enter Airtable base id" max_length="100" value={{form.airtable_credentials.value}} id="id_airtable_base">
                                </div>  
                                <div class="form-group">
                                    <input type="text" class="form-control" name="airtable_table_name_top_messages" placeholder="Enter top messages table name" max_length="100" value={{form.airtable_credentials.value}} id="id_airtable_table_name_top_messages">
                                </div>
                                <!--
                                <div class="form-group">
                                    <input type="password" class="form-control" name="airtable_table_name_garden" placeholder="Enter garden messages table name" max_length="100" id="id_airtable_table_name_garden">
                                </div>
                                --> 
                            </div>
                        </div>
                        <!--                         
                        <label> Monitored guilds: </label>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group guilds-container">
                                    <input type="text" class="form-control" name="monitored_guilds" placeholder="Press enter or add a comma after each guild name" id="monitored_guilds">
                                    <ul id="guilds_list"></ul>
                                </div>           
                            </div>
                            <div class="col-4">
                            </div>
                        </div> -->
                        
                        <label for="id_monitored_channels"> Monitored channels: </label>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group channels-container">
                                    <input type="text" class="form-control" name="monitored_channels" placeholder="Press enter or add a comma after each channel name" id="id_monitored_channels" value={{form.monitored_channels.value}}>
                                    <ul id="channels_list"></ul>
                                </div>           
                            </div>
                            <div class="col-4">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="btn-div col-lg-6">
                                <button type="submit" class="btn btn-light cancel-btn"> Cancel </button>
                            </div>
                            <div class="btn-div col-lg-6 text-right">
                                <button type="submit" class="btn btn-dark save-btn"> Save </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>


<!-- <div>
    <legend> Community Profile Information: </legend>

    {% if user.is_authenticated %}
        {% if form.non_field_errors %}
            <div class="alert alert-dismissible alert-danger">
                <strong>{{form.non_field_errors}}</strong>
            </div>
        {% endif %}

        <p>This page let's you set up your community.</p>

        <form method="POST">
            {% csrf_token %}

            <p>
                <label for="id_community_name">Community name:</label>
                <input type="text" name="community_name" placeholder="Enter community name" value={{form.community_name.value}} maxlength="100" id="id_community_name">
            </p>
            <p>
                <label for="id_airtable_credentials">Airtable credentials:</label>
                <textarea name="airtable_credentials" cols="40" rows="5" id="id_airtable_credentials">{{form.airtable_credentials.value}}
                </textarea>

                <span class="helptext">The Airtable key, base name, and table name associated with Stigsite</span>
            </p>

            <p>
                <label for="id_monitored_guilds">Monitored guilds:</label>
                <textarea name="monitored_guilds" cols="40" rows="5" id="id_monitored_guilds">
                {{form.monitored_guilds.value}}
                </textarea>

                <span class="helptext">A list of Discord guilds (servers) the site will listen to</span>
            </p>

            <p>
                <label for="id_promotion_threshold">Promotion threshold:</label>
                <input type="number" name="promotion_threshold" value={{form.promotion_threshold.value}} required id="id_promotion_threshold">
            </p>
            <p>
                <label for="id_enable_twitter_handle_request">Enable twitter handle request:</label>
                <input type="checkbox" name="enable_twitter_handle_request" id="id_enable_twitter_handle_request"{% if form.enable_twitter_handle_request.value %} checked {% endif %}>

            </p>
            <input type="submit" name="submit" value="Update">
        </form>

    {% endif %}
</div> -->



{% endblock content %}

discordlogin/templates/discordlogin/form.html
Airtable Credentials

<input type="text" id="air-table-key">
<input type="text" id="air-table-base-id">
<input type="text" id="air-table-tm-name">
<input type="text" id="air-table-gm-name">

Promotion Threshold
<input type="number" id="threshold" min=0 name="threshold" placeholder=0>

Django Site Id
<select class="form-control form-control-md">
    <option>Each of the site frameworks</option>
</select>



Enable Twitter Handle Request
<div class="form-check">
    <input class="form-check-input" type="checkbox" value="twitterHandleRequest">
    <label class="form-check-label" for="twitterHandleRequest">
        Enable Twitter Handle Request
    </label>
</div>


<button type="button" class="btn btn-submit">Update</button>

discordlogin/templates/discordlogin/profile.html
{% extends "stigapp/base.html" %}
{% load static %}

{% block content %}

<div class="card profile-container mt-4 mb-4">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-header"> 
            <h3 class="pt-2"> Profile Information </h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="form-group col-lg-6">
                    <label for="id_username"> Discord handle: </label>
                    <input type="text" class="form-control" name="username" value={{form.username.value}} placeholder="Enter username" max_length="100" id="id_username" required>
                </div>
                <div class="form-group col-lg-6">
                    <label for="id_twitter_handle"> Twitter handle: </label>
                    <input type="text" class="form-control" name="twitter_handle" value={{form.twitter_handle.value}} placeholder="Enter twitter handle" max_length="100" id="id_twitter_handle">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label for="id_first_name"> First name: </label>
                    <input type="text" class="form-control" name="first_name" value={{form.first_name.value}} placeholder="Enter first name" max_length="100" id="id_first_name" required>
                </div>
                <div class="form-group col-lg-6">
                    <label for="id_last_name"> Last name: </label>
                    <input type="text" class="form-control" name="last_name" value={{form.last_name.value}} placeholder="Enter last name" max_length="100" id="id_last_name" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_email"> Email: </label>
                <input type="email" class="form-control" name="email" value={{form.email.value}} placeholder="Enter email" max_length="255" id="id_email">
            </div>
        </div>
        <div class="card-footer">
            <div class="row">  
                <div class="btn-div col-lg-6">
                    <a class="btn btn-light cancel-btn" href="{% url 'home' %}"> Cancel </a>
                </div>
                <div class="btn-div col-lg-6">
                    <button type="submit" class="btn btn-dark save-btn"> Save </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock content %}